AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 with Apache, PHP and WP
Parameters:
  NetworkStackName:
    Description: Name the active CloudFormation stack that contains the networking
      resources that will be used in this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: SampleNetworkCrossStack
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0ab193018f3e9351b
      InstanceType: t2.micro
      KeyName: macbook@400048mbp
      SubnetId: !ImportValue PublicSubnet1
      SecurityGroupIds:
        - !ImportValue MySGWP
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          dnf update -y
          dnf install -y apache2 php
          systemctl enable apache2
          systemctl start apache2
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzvf latest.tar.gz
          cp -R wordpress/* .
          rm -rf wordpress latest.tar.gz
          chown -R www-data:www-data *
          chmod -R 755 wp-content
Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Export:
      Name: EC2InstanceId
