AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 with Apache, PHP and WP

Parameters: 
  ImageId: 
    Description: "EC2 Image ID"
    Type: String
  SSHKeyName: 
    Description: "SSH Key Name"
    Type: String
  InstanceType: 
    Description: Select an Instance Type
    Type: String 
    Default: t2.micro 
    AllowedValues: 
      - t2.micro
      - t2.medium

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref ImageId
      KeyName: !Ref SSHKeyName
      SubnetId: !ImportValue PublicSubnet1
      SecurityGroupIds:
        - !ImportValue MySGWP
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          dnf update -y
          dnf install wget php-mysqlnd httpd php-fpm php-mysqli php-json php php-devel -y
          systemctl enable httpd
          systemctl start httpd
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzvf latest.tar.gz
          cp -R wordpress/* .
          rm -rf wordpress latest.tar.gz
          chown -R apache:apache *
          chmod -R 755 wp-content
Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Export:
      Name: EC2InstanceId
