AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 with Apache, PHP and WP

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0ab193018f3e9351b  #ami-0715c1897453cabd1
      InstanceType: t2.micro
      KeyName: macbook@400048mbp
      SubnetId: !ImportValue PublicSubnet1
      SecurityGroupIds:
        - !ImportValue MySGWP
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          dnf update -y
          dnf install -y mysql php-mysqlnd httpd php-fpm php-mysqli mariadb105-server php-json php php-devel
          systemctl enable httpd
          systemctl start httpd
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzvf latest.tar.gz
          cp -R wordpress/* .
          rm -rf wordpress latest.tar.gz
          chown -R apache:apache *
          chmod -R 755 wp-content
Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Export:
      Name: EC2InstanceId
