AWSTemplateFormatVersion: '2010-09-09'
Description: "It creates an AWS ELB for WordPress/RDS Project"

Parameters:
  
  Certificates:
    Description: Enter your certificate ARN here to create listeners.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: CertificatesArn
  
  HostedZoneId:
    Description: Enter your Hosted Zone ID here to create Route 53 record.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: HostedZoneId

  Subdomain:
    Description: Enter the subdomain name.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: subdomain.example.com

Resources:
  
  MyLoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      Listeners:
      - InstancePort: '80'
        InstanceProtocol: HTTP
        LoadBalancerPort: '443'
        Protocol: HTTPS
        SSLCertificateId: !Ref Certificates
      SecurityGroups: 
        - !ImportValue MyELBSg
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      Subnets: 
        - !ImportValue PublicSubnet1
      Scheme: internet-facing

# Route 53 Record Set to sent traffic to ELB.
  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Subdomain
      Type: A
      TTL: '300'
