AWSTemplateFormatVersion: '2010-09-09'
Description: "It creates an AWS ELB for WordPress/RDS Project"

Parameters:
  
  Certificates:
    Description: Enter your certificate ARN here to create listeners.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: CertificatesArn
  
  HostedZoneId:
    Description: Enter your Hosted Zone ID here to create Route 53 record.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: HostedZoneId

  Subdomain:
    Description: Enter the subdomain name.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: subdomain.example.com

Resources:
  
  MyLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: MyLoadBalancer
      SecurityGroups: 
        - !ImportValue MyELBSg
      Subnets: 
        - !ImportValue PublicSubnet1
        - !ImportValue PublicSubnet2
      Scheme: internet-facing
      Type: application
  
  ELBTargetG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: 1
      HealthCheckIntervalSeconds: 20
      HealthCheckTimeoutSeconds: 20
      Name: ELBTargetG
      Port: 80
      Protocol: 'HTTP'
      Targets: 
        - Id: !ImportValue EC2InstanceId
        - Port: 80
      TargetType: instance
      UnhealthyThresholdCount: 5
      VpcId: !ImportValue MyVPC

  MyELB443Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates: 
        - !Ref Certificates
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref ELBTargetG
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 443
      Protocol: HTTPS
  
  MyELB80Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref ELBTargetG
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP

# Route 53 Record Set to sent traffic to ELB.
  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget: 
        - DNSName: !Ref MyLoadBalancer
          HostedZoneId: !Ref HostedZoneId
      Name: !Ref Subdomain
      Type: A
      TTL: '300'
