AWSTemplateFormatVersion: "2010-09-09"
Description: "It creates an AWS RDS database"
Parameters:
  NetworkStackName:
    Description: Name the active CloudFormation stack that contains the networking
      resources that will be used in this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: SampleNetworkCrossStack
  MasterUsername:
    Description: Write the username for your Database
    Type: String
    MinLength: 5
    MaxLength: 25
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: masterusername
  MasterUserPassword:
    Description: Write the password for your Database
    Type: String
    MinLength: 5
    MaxLength: 25
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: masterpassword
Resources:
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupName: MyDBSubnetGroup
      DBSubnetGroupDescription: My DB Subnet Group
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2
  RdsInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      Engine: MariaDB
      DBInstanceIdentifier: MyDBInstance
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBInstanceClass: db.t2.micro
      VPCSecurityGroups:
        - !ImportValue MySGRDS
      AvailabilityZone: !Select [0, !GetAZs '']
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: RdsInstance
        - Key: Purpose
          Value: WordPress