### Not finished yet
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: mustafatahran.net
      HostedZoneConfig:
        Comment: DNS Zone for example.com
  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: example.com
      Type: A
      TTL: '300'
      ResourceRecords:
        - 192.0.2.1