AWSTemplateFormatVersion: "2010-09-09"
Description: A Network Template for WordPress and RDS Project
Resources:  
  
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: 10.0.0.0/23
      Tags:
        - Key: Name
          Value: MyVPC
        - Key: Purpose
          Value: WP/RDS
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/25
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1
        - Key: Purpose
          Value: WP/RDS
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.129/25
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2
        - Key: Purpose
          Value: WP/RDS
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/25
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet1
        - Key: Purpose
          Value: WP/RDS
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.129/25
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet2
        - Key: Purpose
          Value: WP/RDS
  
# EC2 Instance Security Group
  MySGWP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: new security group for EC2 with WordPress
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp     # Needed for connecting to Load Balancer.
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !Ref MyELBSg
      - IpProtocol: tcp     # Needed for entering into Instance by SSH.
        FromPort: 22
        ToPort: 22
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp     # Needed for the update of EC2 Instance on internet.
        FromPort: 443
        ToPort: 443
        CidrIp: "0.0.0.0/0"  
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: "0.0.0.0/0"
      Tags:
      - Key: Name
        Value: MySG-WP
      - Key: Purpose
        Value: WP
  
# RDS Security Group  
  MySGRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: new security group for RDS
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !Ref MySGWP    # Needed for connecting to EC2 Instance.
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: "10.0.0.0/0" 
      Tags:
      - Key: Name
        Value: MySG-RDS
      - Key: Purpose
        Value: RDS

# Elastic Load Balancer Security Group
  MyELBSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: new security group for ELB
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: "0.0.0.0/0"
      Tags:
      - Key: Name
        Value: MySG-ELB
      - Key: Purpose
        Value: ELB

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
  
  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  
  PublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2
  
  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: MyIGW
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyIGW
  
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyIGW

Outputs:
  MyVPC: 
    Description: The VPC created for WordPress and RDS project.
    Value: !Ref MyVPC
    Export:
      Name: MyVPC
  MySGRDS:
    Description: the Security Group created for RDS 
    Value: !Ref MySGRDS
    Export:
      Name: MySGRDS
  MySGWP:
    Description: the Security Group created for the instance hosting WordPress
    Value: !Ref MySGWP
    Export:
      Name: MySGWP
  MyELBSg:
    Description: the Security Group created for the Elastic Load Balancer
    Value: !Ref MyELBSg
    Export:
      Name: MyELBSg
  PrivateSubnet1:
    Description: the Private Subnet hosting RDS on 1.AZ
    Value: !Ref PrivateSubnet1
    Export:
      Name: PrivateSubnet1
  PublicSubnet1: 
    Description: the Public Subnet hosting WordPress on 1.AZ
    Value: !Ref PublicSubnet1
    Export:
      Name: PublicSubnet1
  PrivateSubnet2:
    Description: the 2nd Private Subnet on 2.AZ
    Value: !Ref PrivateSubnet2
    Export:
      Name: PrivateSubnet2
  PublicSubnet2: 
    Description: the 2nd Public Subnet on 2.AZ
    Value: !Ref PublicSubnet2
    Export:
      Name: PublicSubnet2